# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1c68ad4002239ca35b97620835b32bd57c8225208cb62554f3bc6b360a89e0709ffa34f9dbb93382f58fc81daf517f66799c50acc4597a902a237fdc257bfa2

test:
  secret_key_base: cddd680daf4434e87b34808e13a12aef4d8ee99f679bcc3c9a3cce57d12520a01f792efd69579427ea0393f1d9973ce09012f84cf0025cb3700523a5e78feade

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
